---
- name: update web server
  hosts: all

  tasks:
    - name: download git
      become: yes
      yum:
        name: git
        state: latest
        update_cache: true

    - name: clone git repo
      become: no
      git:
        repo: 'https://github.com/mrigby-cloud/just-a-repo.git'
        version: master
        dest: ./just-a-repo
        accept_hostkey: yes

    - name: Add apache
      become: yes
      package:
        name: httpd
        state: present

    - name: Add stock check script to root crontab
      become: yes
      cron:
        name: "stock check script"
        minute: *
        job: "/home/ec2-user/just-a-repo/stock-check-for"
        user: root

    - name: Start apache
      become: yes
      service:
        name: httpd
        state: started
        enabled: yes
      
  #tasks:
  #- name: write a test file in /tmp
  #  template:
  #   src: ansible_test_file
  #    dest: /tmp/